### ISSUE TITLE
Chatbox AppImage version may change unintendedly

### ISSUE THREAD

**Issue by ariejan** [frederikstroem/PKGBUILDs#4]
**Expected behaviour** - The pinned version of the AppImage is downloaded.

**Actual behaviour** - The latest version of the AppImage is downloaded. Not necessarily matching the version specified in `PKGBUILD`

**Details**

Right now the `PKGBUILD` is using the redirect URL to download the AppImage:

`https://chatboxai.app/install_chatbox/linux`

This will always download the latest release (1.4.1). However, `PKGBUILD` is pinned to a single version (1.4.0).

This means that the `makepkg -si` will fail:

```
makepkg -s
==> Making package: chatbox-appimage 1.4.0-1 (Fri 13 Sep 2024 09:22:12 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading linux...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    92  100    92    0     0    185      0 --:--:-- --:--:-- --:--:--   185
100  101M  100  101M    0     0  39.9M      0  0:00:02  0:00:02 --:--:-- 56.6M
==> Validating source files with sha512sums...
    linux ... FAILED
==> ERROR: One or more files did not pass the validity check!
```

**Proposed solution**: 

Use the actual download link in `PKGBUILD`. It seems the upstream developer is not longer posting releases/tags on Github. However, download URLs can be pinned to versions, as both of the following URLs are working:

 - https://download.chatboxai.app/releases/Chatbox-1.4.0-x86_64.AppImage
 - https://download.chatboxai.app/releases/Chatbox-1.4.1-x86_64.AppImage

**Notes**

I did a quick edit of `PKGBUILD` to use the 1.4.0 app image, and that works just fine. I'll post a PR later if/when I have time.

**Comment by frederikstroem** [comment]
Hi @ariejan,

Thank you very much for pointing that out! I have updated the source URL in the PKGBUILD using your proposed solution.
